config/routes.rb
Rails.application.routes.draw do
  root 'wish_maps#index'
  resources :wish_maps
end

app/models/country_flag.rb
class CountryFlag < ActiveRecord::Base

  class << self
    def all_flag
      if Redis.current.get('CountryFlag::all_flag')
        JSON.parse(Redis.current.get('CountryFlag::all_flag'))
      else
        list = all.to_a.map(&:attributes)
        Redis.current.set('CountryFlag::all_flag', list.to_json)
        list
      end
    end
  end
end

app/models/wish_map.rb
class WishMap < ActiveRecord::Base
  serialize :wish, Array
  serialize :been, Array

  after_create :update_distance

  def countries
    query_list = wish.any? ? wish : been
    CountryFlag.where isoAlpha3: query_list
  end

  def update_distance
    coordinates = [39.938086, 116.426065]
    distance = countries.map do |country|
      distance = Geocoder::Calculations.distance_between(coordinates, country.coordinate.split(',')).to_f
      distance = 0 if distance.nan?
      distance.round(2)
    end.sum

    self.update distance: distance
  end

  def round_trip_percent
    (distance / 40076.0).round(4) * 100
  end

  def wining_percent
    molecules = self.class.where('distance > :distance', distance: distance).count.to_f
    all_count = self.class.count.to_f
    (1 - (molecules/all_count)) * 100
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/wish_maps_controller.rb
class WishMapsController < ApplicationController
  layout 'wishmap'
  before_action :set_wechat

  def index
  end

  def create
    @wish_map = WishMap.create wish_map_params
    Redis.current.set @wish_map.uuid, '1'
    redirect_to wish_map_path(id: @wish_map.uuid)
  end

  def show
    @wish_map = WishMap.find_by uuid: params[:id]
    @title = if @wish_map.been.any?
               "2016足迹地图"
             else
               "2017心愿地图"
             end
  end

  private

  def wish_map_params
    params.permit({ been: [] },{ wish: [] }, :uuid)
  end

  def set_wechat
    @wechat = Wechat.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/wish_maps_helper.rb
module WishMapsHelper
  def map_image(path)
    host = 'http://uniqueway.b0.upaiyun.com/2017_wishmap/'
    image_tag "#{host}#{path}"
  end

  def title_bar(text)
    raw "
    <h2 class='title_bar'>
      #{map_image 'title_bar_left.png'}
      <span>#{text}</span>
      #{map_image 'title_bar_right.png'}
    </h2>
    "
  end

  def share_desc(bool)
    if bool
      # """
      # 未来还有#{@wish_map.distance * 2}里路等着你,你只需决定出发。2017年开始，做个有『鸡』情的人，让别人『鸡』妒到底！
      # """
      countries = CountryFlag.where isoAlpha3: @wish_map.wish
      if countries.count > 1
        if countries.count > 3
          """ 2017年，我要去这些地方：#{countries[0..2].collect(&:c_name).join(',')}...等五个国家及地区，立贴为证！
          """
          
        else
          """ 2017年，我要去这些地方：#{countries.collect(&:c_name).join(',')}，立贴为证！
          """
          
        end
      else
        """
        2017年，我要去#{countries.first.c_name}，立贴为证！
        """
      end
    else      
      """ 2016年，我游历了#{@wish_map.been.count}个国家及地区，已经环游了#{number_to_percentage @wish_map.round_trip_percent, precision: 0}的世界！击败了 #{number_to_percentage @wish_map.wining_percent, precision: 0}的人。
      """
    end.strip
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GameUniquewayCom</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/wishmap.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= @title || "心愿地图" %></title>
  <meta name="viewport" content="width=device-width,height=device-height,initial-scale=1,user-scalable=0" />
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body id="wishmap">
  <%= yield %>
</body>
<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
</html>
<script>
(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
})(window,document,'script','//www.google-analytics.com/analytics.js','ga');

ga('create', 'UA-56818489-1', 'auto');
ga('send', 'pageview');
</script>

app/views/shared/_wechat.html.erb
<script type="text/javascript" src="https://res.wx.qq.com/open/js/jweixin-1.0.0.js"></script>
<script>
document.addEventListener('DOMContentLoaded', function(){
  wx.config({
    debug: false,
    appId     : "<%= @wechat.app_id %>",
    timestamp : "<%= @wechat.timestamp %>",
    nonceStr  : "<%= @wechat.noncestr %>",
    signature : "<%= @wechat.signature(request.original_url) %>",
    jsApiList: [
    'checkJsApi',
    'onMenuShareTimeline',
    'onMenuShareAppMessage',
    'onMenuShareQQ',
    'onMenuShareWeibo',
    'hideMenuItems',
    'showMenuItems',
    'hideAllNonBaseMenuItem',
    'showAllNonBaseMenuItem'
    ]
  })
  var set_up_share;

  set_up_share = function(data) {
    var share_data;
    title = document.getElementById('title').value
    desc = document.getElementById('desc').value
    share_data = {
      title: desc,
      imgUrl: 'http://uniqueway.b0.upaiyun.com/2017_wishmap/108x108.png',
      link: location.href,
      success: function() {
        ga('send', 'event', 'button', 'share', '2017_wishmap');
      },
      cancel: function() {
        return 0;
      }
    };
    wx.onMenuShareTimeline(share_data);
    other_data = JSON.parse(JSON.stringify(share_data))
    other_data.title = title
    other_data.desc = desc
    wx.onMenuShareAppMessage(other_data);
    wx.onMenuShareQQ(other_data);
    wx.onMenuShareWeibo(other_data);
  };
  wx.ready(function() {
    set_up_share();
  })
}, false);

</script>

app/views/wish_maps/_form.html.erb
<%= form_tag(wish_maps_path, method: "POST", class: 'selection_list') do %>
  <%= hidden_field_tag('uuid', SecureRandom.uuid) %>
  <%= link_to "生成我的足迹地图", 'javascript:;', class: 'submit_button' %>

  <% continent_set = CountryFlag.all_flag.group_by {|d| d['continent']} %>
  <% ["亚洲", "欧洲", "北美洲", "大洋洲","非洲", "南美洲",  "南极洲"].each do |continent_name| %>
    <% list = continent_set[continent_name] %>
    <% if list && list.count > 1 %>
    <div class="continent clearfix">
      <h5><%= continent_name %><span class='arrow-up'></span></h5>
      <div class="flag_list hide">
        <% list.each do |flag| %>
        <span class="flag_item">
          <input type='checkbox' id="flag<%= flag["id"] %>" value="<%= flag["isoAlpha3"] %>" />
          <label style='background-image:url(<%= "#{flag['url']}!w90" %>)' for="flag<%= flag["id"] %>">
            <span>
              <%= flag["c_name"] %>
            </span>
          </label>
        </span>
        <% end %>
      </div>
    </div>
    <% end %>
  <% end %>
  
<% end %>

app/views/wish_maps/_introduce_page.html.erb
<div class="introduce_page">
  <div class="banner">
    <div class='fix_item banner_star'>
      <%= map_image 'banner_star.png' %>
    </div>
    <div class='fix_item tiny_star'>
      <%= map_image 'tiny_star.png' %>
    </div>
    <div class='fix_item left_bottom_cloud'>
      <%= map_image 'left_bottom_cloud.png' %>
    </div>
    <div class='fix_item left_up_cloud'>
      <%= map_image 'left_bottom_cloud.png' %>
    </div>
    
    <div class='fix_item right_bottom_cloud'>
      <%= map_image 'right_bottom_cloud.png' %>
    </div>
    <div class='fix_item right_up_cloud'>
      <%= map_image 'right_up_cloud.png' %>
    </div>
    <div class="fix_item wheel">
      <%= map_image 'circle.png' %>
    </div>
    <div class="body">
      <%= map_image 'banner_body.png' %>
    </div>
  </div>
  <div class='desc'>
    <p class='hide'>又到一年一度的“年底大盘点”！</p>
    <p class='hide'>2016年你买了几个包？</p>
    <p class='hide'>读了几本书？</p>
    <p class='hide'>跑了几次步？</p>
    <p class='hide'>……</p>
    <p class='hide'>对于爱折腾的你来说，以上这些还不够！</p>
    <p class='hide'>年底总结必然要有各种地名大串烧！</p>
    <p class='hide'>2016年，你走过哪些路？</p>
    <p class='hide'>未来，你还要环游几个世界？</p>
    <div class="hide part button_group">
      <div class="button">
        <%= link_to '晒2016年的足迹', 'javascript:;', data:{ type: 'been' } %>
      </div>
      <div class="button">
        <%= link_to '制作2017年心愿地图', 'javascript:;', data:{ type: 'wish' } %>
      </div>
    </div>
  </div>
</div>

app/views/wish_maps/index.html.erb
<!-- http://uniqueway.b0.upaiyun.com/2017_wishmap/index/index_bg.png -->
<%= render 'introduce_page' %>

<div class="page-container hide">
  <div class="section wish_bg">
    <%= title_bar '2017年心愿地图' %>
    <p class='first'>去法国买几个包；</p>
    <p>去荷兰看橱窗女郎；</p>
    <p>去英国的酒吧喝个够；</p>
    <p>去美国自驾看最美公路；</p>
    <p>去日本跑一场樱花马拉松；</p>
    <p>去……</p>
    <p class='bottom_fix_text'>
      列出未来你想去的地方，点亮你的心愿地图——
    </p>
    <div class='slide_down'>
      <%= map_image 'slide_down.png' %>
    </div>
  </div>
  <div class="section flags">
    <%= title_bar '2016年 我已经走过这些地方' %>
    <div id='map_container'>
    </div>
    <%= render 'form' %>
  </div>
</div>


<%= render '/shared/wechat' %>

<%= hidden_field_tag :title, '无二之旅2017心愿地图' %>
<%= hidden_field_tag :desc, '无二之旅，实现你每一个关于旅行的小心愿。' %>

app/views/wish_maps/show.html.erb
<div class="page-container">
  <%= title_bar @wish_map.wish.any? ? '2017心愿地图' : '2016我的足迹' %>

  <div class="result">
    <% if @wish_map.wish.any? %>
    <% countries = CountryFlag.where(isoAlpha3: @wish_map.wish).pluck(:c_name) %>
    <% if countries.count > 3 %>
    <p><span class='small'><%= countries[0..2].join(',') %>…<%= countries.count %>个国家及地区</span></p>
    <% else %>
    <p><span class='small'><%= countries.join(',') %></span></p>
    <% end %>
    <p class="more">未来还有<span><%= @wish_map.distance * 2 %></span>里路等着你，</p>
    <p class='light'>你只需决定出发。</p>
    <p class='light'>2017年开始，</p>
    <p class='light'>做个有『鸡』情的人，</p>
    <p class='light'>让别人『鸡』妒到底！</p>
    <% else %>
    <% countries = CountryFlag.where(isoAlpha3: @wish_map.been).pluck(:c_name) %>
    <% if countries.count > 3 %>
    <p>2016年我去了<span class='small'><%= countries[0..2].join(',') %>…<%= countries.count %>个国家及地区</span></p>
    <% else %>
    <p>2016年我去了<span class='small'><%= countries.join(',') %></span></p>
    <% end %>
    <p>走过<span><%= @wish_map.distance * 2 %></span>里路</p>
    <p>已经环游了<span><%= number_to_percentage @wish_map.round_trip_percent, precision: 0 %></span>的世界！</p>
    <p>击败了 <span><%= number_to_percentage @wish_map.wining_percent, precision: 0 %></span> 的人</p>
    <% end %>
  </div>
  <div class='tips_block'>
    <p>搜索公众号<span>"无二之旅"</span>，添加关注，</p>
    <p>回复你想去的<span>目的地+心愿地图</span></p>
    <p class='small'>(如回复：日本 心愿地图)</p>
    <p>即可领取 <span class='big'>666</span> 元的旅行基金！</p>
  </div>
  
  
  <div class="bottom_block">
    <% if Redis.current.get @wish_map.uuid %>
      <%= link_to @wish_map.wish.any? ? "晒心愿" : "去炫耀", 'javascript:;', class: 'share_button go' %>
      <% Redis.current.del @wish_map.uuid %>

    <% else %>
      <%= link_to "我也要玩", wish_maps_path(), class: 'share_button' %>
    
    <% end %>
  </div>
</div>

<div class="share_block">
  <%= map_image "arrow.png" %>
  <h5>
    点此处分享给好友或朋友圈
  </h5>
</div>

<%= render '/shared/wechat' %>
<%= hidden_field_tag :title, @wish_map.wish.any? ? '2017心愿地图' : '2016我的足迹' %>
<%= hidden_field_tag :desc, share_desc(@wish_map.wish.any?) %>